// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_At6Zn7yU_bU9LIkg1OV_UflNbz9W1Y',
    appId: '1:1045232562713:android:6c7fecab6b3c0a1c1ff088',
    messagingSenderId: '1045232562713',
    projectId: 'luciferai-3b049',
    storageBucket: 'luciferai-3b049.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs3aylUMnH1Ktp_UQeffYkDbEk3AExX4k',
    appId: '1:1045232562713:ios:17d442dcc4a2534d1ff088',
    messagingSenderId: '1045232562713',
    projectId: 'luciferai-3b049',
    storageBucket: 'luciferai-3b049.firebasestorage.app',
    iosClientId: '1045232562713-e41324dlu6b3d3497fanis0frbfthq0k.apps.googleusercontent.com',
    iosBundleId: 'com.ruralcare.ruralcare',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb16_YSuW9Xj3Oy_CztCd0NVYzlbrgJA0',
    appId: '1:1045232562713:web:b65b79d4df8f413a1ff088',
    messagingSenderId: '1045232562713',
    projectId: 'luciferai-3b049',
    authDomain: 'luciferai-3b049.firebaseapp.com',
    storageBucket: 'luciferai-3b049.firebasestorage.app',
    measurementId: 'G-S8FK5BT8D9',
  );
}
